### ISSUE TITLE
feat: add a setting(s) to improve the experience on laptops

### ISSUE THREAD

**Issue by ispanos** [ublue-os/ublue-update#101]
I would like to disable updates when on battery, but with the `min_battery_percent` I cannot do it. I have set my ThinkPad to charge up to 85%, thus if I set `min_battery_percent = 100`, my laptop will never update. Any lower that 85% and I will be updating even on battery. We either need to add something like `always-update-on-ac`, or `update-on-battery`.

I'm not sure how to check, but we decide on how this should be solved, all I need are instructions on how to check if the laptop is charging, then I can try opening a PR.

**Comment by larina3315** [comment]
you could disable auto-update scripts/jobs provided by ublue and create a timer/cron job to check your charge/battery status after a given interval and auto-update accordingly ?

**Comment by ispanos** [comment]
I think I was wrong about this issue.

Can someone confirm that [this line](https://github.com/ublue-os/ublue-update/blob/593382b98721fff8f65026bb9e1b3d8ff895012d/src/ublue_update/update_inhibitors/hardware.py#L32) means that I can safely set the threshold to 100% and still get updates when I plug in my laptop, regardless of the battery level?

**Comment by gerblesh** [comment]
Yes, if you set the `min_battery_percent` to `100` you're able to force it to only update when on AC, in theory you could also do `1000` or something else which is completely unattainable in normal circumstances, but with the `or` in that line, the check would pass regardless if your laptop was on AC

**Comment by ispanos** [comment]
Thank you!
