### ISSUE TITLE
Apply a lesser priority to ublue-update systemd preset

### ISSUE THREAD

**Issue by Zeglius** [ublue-os/ublue-update#120]
Currently (at the time of writing, 2024-07-14) ublue-update rpm includes a systemd preset (which gets installled at `/usr/lib/systemd/system-preset/00-ublue-update.preset`).

The problem comes with the prefix `00`.

> All preset files are sorted by their filename in lexicographic order, regardless of which of the directories they reside in. If multiple files specify the same unit name, the entry in the file with the lexicographically earliest name will be applied.
>
>    ~ *https://www.freedesktop.org/software/systemd/man/latest/systemd.preset.html*

Basically, by using `00`, is applied above all other presets, which is way too high for a preinstalled package.

`ublue-update` is used in Bazzite, Bluefin, and Aurora. Still, is by far too restrictive for any of these images, if their teams wish to use systemd presets, as with prefix `00`, `ublue-update.timer` will always be enabled.

#### There are workaround to use systemd presets and disable `ublue-update.timer`?

Yes. As per quote of systemd.preset:
> Files in /etc/ are reserved for the local administrator, who may use this logic to override the preset files installed by vendor packages.

However, we should keep sane defaults at /usr, as these are easier to maintain, rather than fiddling with /etc at runtime (this includes /etc manipulation at build time, aka, Containerfiles)

#### Would this change break anything?

No. 
If the concern is a vendor package from outside the ublue-os ecosystem overriding ublue-update presets in an unintentional way, that case
is very difficult to be given.
The only way someone can accidentally override is by using a preset file like this:

```
#/usr/lib/systemd/system-preset/00-dummy.preset
disable *
```

Which would, in fact, would override **ALL** preset files. Something that no sane package would do.
In fact, systemd themselves recommend to not ship systemd presets files, other than distro developers themselves.

> It is not recommended to ship preset files within the respective software packages implementing the units, but rather centralize them in a distribution or spin default policy, which can be amended by administrator policy, see below.
>
>   ~ *https://www.freedesktop.org/software/systemd/man/latest/systemd.preset.html*

#### What benefits would bring this change?

1. There is no downside/risk of breaking anything.
2. Allows more flexibility for other images (Bazzite, Bluefin, Aurora) to move defaults (like services activation) to a more static approach (in this case, disabling `ublue-update.timer` with systemd presets).

**Comment by gerblesh** [comment]
fixed in: https://github.com/ublue-os/ublue-update/pull/121
