### ISSUE TITLE
`loginctl` commands need to be changed since Fedora 41 (systemd v256)

### ISSUE THREAD

**Issue by fiftydinar** [ublue-os/ublue-update#132]
`--output=json` does not work anymore, just using `-j` is sufficient (however, this will break F40 & older, so some dynamic logic needs to be applied for this)

See this issue for more details:
https://github.com/systemd/systemd/issues/34901

If this is not solved, notifications will stop working if configured

**Comment by bsherman** [comment]
The PR ( #133 ) is part of the solution, but it would break notifications on F40.

I think we need to check systemd version and use the correct option per version.

**Comment by bsherman** [comment]
Closed by #134
