### ISSUE TITLE
Update checks

### ISSUE THREAD

**Issue by EyeCantCU** [ublue-os/ublue-update#23]
Expanding on: https://github.com/ublue-os/ublue-update/issues/9

Currently rpm-ostree, flatpak, and distrobox do not provide built in ways of handling update checks. This has been circumvented for rpm-ostree by using Skopeo to compare the digest on the installed system to the one available in the hosted image.

However, that still leaves flatpak and distrobox.

Handling flatpak update checks could be complicated as, while it primarily is ostree based, there are repositories in the wild (namely Fedora's) that rely on the usage of OCI images instead. This would require two ways of checking for flatpak updates and verification of what kind of repository is in use so that we know which update check methodology we need to use for that specific repository. Ideas on how to handle this are very welcome.

As for distrobox, things are also complicated. For image updates on their own, we could easily use Skopeo again. It would pretty much be a copy and paste of what we already have for system updates that cycles through each installation, and compares digests. However, for on image update checks, I'm at a loss for ideas so anything there would be appreciated.

Thank you all for reading this. I hope you all have a great day :)

**Comment by cr7pt0gr4ph7** [comment]
The switch to [topgrade](https://github.com/topgrade-rs/topgrade) in #102 introduced support for flatpack and distrobox, so this issue could arguably be closed as "resolved".

**Comment by gerblesh** [comment]
Thanks! Yes topgrade resolves this
