### ISSUE TITLE
System level vs User updates

### ISSUE THREAD

**Issue by gerblesh** [ublue-os/ublue-update#5]
goal: keep the update system unified and linear, update the user applications after system apps are updated

Currently this script is designed to run as a normal user, not as root or systemwide. The problem is that people may have some rootful distroboxes, or maybe you need root to update rpm-ostree, or possibly something else entirely, and it would be good to build a foundation for doing both userspace and system updates.

**Comment by akdev1l** [comment]
you could split the directory structure into two:

```
/etc/ublue-update.d/system
/etc/ublue-update.d/user
```

then on the script choose which scripts to run based on `UID==0`, if `UID==0` loop through `/etc/ublue-update.d/system` else loop through `/etc/ublue-update.d/user`

then you'd have 2 timers, one for `system` and one for `user` (or as many users as the system would have)

**Comment by gerblesh** [comment]
closed with: https://github.com/ublue-os/ublue-update/pull/62
