### ISSUE TITLE
Auto-sign switch doesn't respect installed tagged version

### ISSUE THREAD

**Issue by bobslept** [ublue-os/ublue-update#74]
I've installed a clean version of bluefin-dx with tag 38 like below.
`rpm-ostree rebase ostree-unverified-registry:ghcr.io/ublue-os/bluefin-dx:38`

```
Deployments:
● ostree-unverified-registry:ghcr.io/ublue-os/bluefin-dx:38
                   Digest: sha256:003d99c3bd135f476013d92b692a4db60cbee6246180b385fc322d959e46fcfa
                  Version: 38.20231001.0 (2023-10-01T12:05:30Z)
```

When the ublue-update has run to automatic switch to the signed image, my installation is switched to the `:latest` tag. 

```
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:latest
                   Digest: sha256:003d99c3bd135f476013d92b692a4db60cbee6246180b385fc322d959e46fcfa
                  Version: 38.20231001.0 (2023-10-01T12:05:30Z)

  ostree-unverified-registry:ghcr.io/ublue-os/bluefin-dx:38
                   Digest: sha256:003d99c3bd135f476013d92b692a4db60cbee6246180b385fc322d959e46fcfa
                  Version: 38.20231001.0 (2023-10-01T12:05:30Z)
```

This is because the `image-info.json` is populated with the latest tag and used by the switching mechanism.  

Is there a reason why we won't extract the tag from the installed version and use the one from image-info.json?

**Comment by gerblesh** [comment]
should be fixed with the PR, just needs some review/testing
