### ISSUE TITLE
Two sets of update scripts

### ISSUE THREAD

**Issue by castrojo** [ublue-os/ublue-update#78]
There's 2 copies of the update scripts, in `/usr/etc/ublue-update.d` and `/etc/ublue-update.d`. 

Can we just keep one copy in `/usr/etc/`?

**Comment by bobslept** [comment]
https://github.com/ublue-os/ublue-update/blob/75fd78b0be2379185874074a4c0c5f2501ddd417/src/ublue_update/config.py#L6-L11

I think these should be changed to `/etc` variant only then. We deploy stuff via `/usr/etc` but on the images it ends up in `/etc/` so I'm not sure why they are both being loaded.

**Comment by bobslept** [comment]
Lets close this one, as we figured it out
