### ISSUE TITLE
System update complete reboot notification

### ISSUE THREAD

**Issue by bobslept** [ublue-os/ublue-update#80]
I've got several "System update complete, reboot for changes..." 

The reboot message makes sense, when there is actually a new deployment there to reboot into. I've seen this message a couple of times today, but there is not actually a need to reboot. 

To avoid confusion this should not always be mentioned I think. Only when it's needed.

**Comment by castrojo** [comment]
Yeah it'd be nice to just be able to set the notifications off.

**Comment by bobslept** [comment]
> Yeah it'd be nice to just be able to set the notifications off.

That is possible. You can set `dbus_notify = false` in `/etc/ublue-update/ublue-update.toml`

**Comment by gerblesh** [comment]
I agree, i'll try to implement this when I have time. It doesn't seem too hard as we already have a python module to check for updates
