### ISSUE TITLE
Disable auto-updates for flatpak

### ISSUE THREAD

**Issue by manan-gup** [ublue-os/ublue-update#95]
Hi, is there any way to disable auto-updates for flatpak? Recently I was using Firefox and flatpak updated it in the background and then the browser started malfunctioning. I would rather update manually than face such a situation.

**Comment by gerblesh** [comment]
You can delete the file for flatpak updates in `/etc/ublue-update.d/system` iirc

**Comment by manan-gup** [comment]
Thanks. I'll try it out.
